wip

diff --git a/scripts/make-graphs b/scripts/make-graphs
--- a/scripts/make-graphs
+++ b/scripts/make-graphs
@@ -2,7 +2,24 @@
 
 set -xe
 
+#T=$(mktemp -d)
+#for mds in "$1/mds*"; do
+#    if [ -r "$mds/stats.db" ]; then
+#        cp -- "$mds/stats.db" "$T/"
+#    elif [ -r "$mds/stats.db.gz" ]; then
+#        cp -- "$mds/stats.db.gz" "$T/"
+#        gunzip "$T/stats.db.gz"
+#    else
+#        printf "can't find stats.db\n" >&2
+#        exit 1
+#    fi
+#done
+
+(cd "$T" && gunzip mds*/root/stats.db.gz) || true
+
 for s in "$(dirname "$0")"/mds-*; do
     s=$(realpath "$s")
-    (cd "$1" && "$s" mds*/*db)
+    (cd "$T" && "$s" mds*/root/*db)
 done
+
+#rm -rf -- "$T"
